## **NUMPY**

In [1]:
v = list(range(1, 6))
v
2 * v
import numpy as np
v = np.arange(1, 6)
v
2 * v

array([ 2,  4,  6,  8, 10])

In [2]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = a * b
c

array([ 4, 10, 18])

In [3]:
import numpy as np

# Create an array of all zeros
a = np.zeros((2, 2))
print(a)
# [[0. 0.]
#  [0. 0.]]

# Create an array of all ones
b = np.ones((1, 2))
print(b)
# [[1. 1.]]

# Create a constant array
c = np.full((2, 2), 7)
print(c)
# [[7. 7.]
#  [7. 7.]]

# Create a 2x2 identity matrix
d = np.eye(2)
print(d)
# [[1. 0.]
#  [0. 1.]]

# Create an array filled with random values
e = np.random.random((2, 2))
print(e)
# Example:
# [[0.91940167 0.08143941]
#  [0.68744134 0.87236687]]

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.47333696 0.26549068]
 [0.16874283 0.4475743 ]]


In [12]:
import numpy as np
a = np.arange(15).reshape(3, 5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [7]:
print(a.shape)

(3, 5)


In [8]:
print(a.ndim)

2


In [9]:
print(a.dtype.name)

int64


In [11]:
import numpy as np
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [14]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]])
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [17]:
import numpy as np
a = np.array([[0, 1, 2, 3],
[10, 11, 12, 13],
[20, 21, 22, 23]])
print(a)

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]]


In [18]:
a = np.array([[0, 1, 2, 3], [10, 11, 12, 13], [20, 21, 22, 23]])
print(a)

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]]


In [19]:
print(a.ndim)

2


In [20]:
print(a.shape)

(3, 4)


In [22]:
import pandas as pd
df = pd.DataFrame({"a": [4, 5, 6],
                   "b": [7, 8, 9],
                   "c": [10, 11, 12]},
index = [1, 2, 3])
type(df)

pandas.core.frame.DataFrame

In [23]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print('pandas imported')

pandas imported


In [24]:
s = pd.Series([1,3,5,np.nan,6,8])
print(s)

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64


In [25]:
dates = pd.date_range('20181001',
periods=6)
print(dates)

DatetimeIndex(['2018-10-01', '2018-10-02', '2018-10-03', '2018-10-04',
               '2018-10-05', '2018-10-06'],
              dtype='datetime64[ns]', freq='D')


In [26]:
df = pd.DataFrame(np.random.randn(6,4),
index=dates, columns=list('ABCD'))
df

A         B         C         D
2018-10-01 -0.215132 -0.501876 -0.223513 -1.748999
2018-10-02 -0.493189  0.746037  0.891269 -1.797408
2018-10-03  0.681164  0.811504 -0.667662  0.860003
2018-10-04 -0.046238  0.249540  0.554151 -1.641598
2018-10-05 -1.466006  0.079825  1.258892 -0.880203
2018-10-06  0.276469  1.406439 -0.375119 -0.138622

In [27]:
df = pd.DataFrame(np.random.randn(3,5),
index=['student1','student2','student3']
, columns=list('ABCDE'))
df

A         B         C         D         E
student1  1.380942  0.032562  1.054682  0.288532 -1.266271
student2 -0.579632  2.089198 -0.449908 -1.064347  0.878613
student3  2.508546 -0.439161 -0.091196 -0.725242  2.802718

In [28]:
df2 = pd.DataFrame({ 'A' : 1.,
'B' : pd.Timestamp('20181001'),
'C' : pd.Series(2.5,index=list(range(4)),dtype='float32'),
'D' : np.array([3] * 4,dtype='int32'),
'E' : pd.Categorical(["test","train","test","train"]),
'F' : 'foo' })
df2

A          B    C  D      E    F
0  1.0 2018-10-01  2.5  3   test  foo
1  1.0 2018-10-01  2.5  3  train  foo
2  1.0 2018-10-01  2.5  3   test  foo
3  1.0 2018-10-01  2.5  3  train  foo

In [29]:
df2.dtypes

A          float64
B    datetime64[s]
C          float32
D            int32
E         category
F           object
dtype: object

## **PANDAS FOR FINANCE**

In [30]:
! pip install pandas_datareader


[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python3 -m pip install --upgrade pip


In [31]:
conda install pandas-datareader

ValueError: The python kernel does not appear to be a conda environment.  Please use ``%pip install`` instead.

In [32]:
# !pip install pandas_datareader
import pandas_datareader.data as web
import datetime as dt
#Read Stock Data from Yahoo Finance
end = dt.datetime(2017, 12, 31)
start = dt.datetime(2016, 1, 1)
df = web.DataReader("AAPL", 'yahoo', start, end)
df.to_csv('AAPL.csv')
df.from_csv('AAPL.csv')
df.tail()

RemoteDataError: Unable to read URL: https://finance.yahoo.com/quote/AAPL/history?period1=1451620800&period2=1514779199&interval=1d&frequency=1d&filter=history
Response Text:
b'<html><meta charset=\'utf-8\'>\n<script>\nif(window != window.top){\ndocument.write(\'<p>Content is currently unavailable.</p><img src="//geo.yahoo.com/p?s=1197757039&t=\'\n    + new Date().getTime() + \'&_R=\'\n    + encodeURIComponent(document.referrer)\n    + \'&err=404\'\n    + \'" width="0px" height="0px"/>\');\n}else{\nwindow.location.replace(\'https://\' + window.location.host + \'/?err=404\');\n}\n</script>\n<noscript>\n<META http-equiv="refresh" content="0;URL=https://finance.yahoo.com/?err=404">\n</noscript></html>'

In [36]:
# !pip install pandas_datareader
import pandas as pd
import pandas_datareader.data as web
import matplotlib.pyplot as plt
import seaborn as sns
import datetime as dt
%matplotlib inline
#Read Stock Data from Yahoo Finance
end = dt.datetime.now()
#start = dt.datetime(end.year-2, end.month,end.day)
start = dt.datetime(2016, 1, 1)
df = web.DataReader("AAPL", 'yahoo', start, end)
df.to_csv('AAPL.csv')
df.from_csv('AAPL.csv')
df.tail()
df['Adj Close'].plot(legend=True, figsize=(12,8), title='AAPL’, label='Adj Close')

SyntaxError: unterminated string literal (detected at line 16) (3843073773.py, line 16)