# **NumPy**

## Phân tích và hiển thị dữ liệu 

In [2]:
v = list(range(1, 6))
print(v)
print(2 * v)

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [3]:
import numpy as np
v = np.arange(1, 6)
print(v)
print(2 * v)

[1 2 3 4 5]
[ 2  4  6  8 10]


In [4]:
fruits = ["apple", "banana", "cherry"] #lists []
colors = ("red", "green", "blue") #tuples ()
animals = {'cat', 'dog'} #sets {}
person = {"name" : "Tom", "age" : 20} #dictionaries {}

In [6]:
x = [60, 70, 80, 90]
print('len(x)=')
print('x[0]=', x[0])
print('x[1]=', x[1])
print('x[-1]=', x[-1])
print('x[1:3]=', x[1:3])

len(x)=
x[0]= 60
x[1]= 70
x[-1]= 90
x[1:3]= [70, 80]


In [8]:
from IPython.display import display
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = a * b
display('c', c)

'c'

array([ 4, 10, 18])

In [9]:
import numpy as np

a = np.zeros((2,2))
display(a)

b = np.ones((1,2))
display(b)

c = np.full((2,2), 7)
display(c)

d = np.eye(2)
display(d)

e = np.random.random((2,2))
display(e)

array([[0., 0.],
       [0., 0.]])

array([[1., 1.]])

array([[7, 7],
       [7, 7]])

array([[1., 0.],
       [0., 1.]])

array([[0.04776293, 0.81070923],
       [0.98656641, 0.70119701]])

In [2]:
import numpy as np
a = np.arange(15)
display(a)

a = a.reshape(3, 5)
display(a)

display(a.shape)
display(a.ndim)
display(a.dtype.name)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

(3, 5)

2

'int64'

In [3]:
import numpy as np
a = np.array([1,2,3,4,5])
display(a)

array([1, 2, 3, 4, 5])

In [4]:
a = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15],
    [16,17,18,19,20]
])
display(a)
display(a.shape)
display(a.ndim)
display(a.dtype.name)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

(4, 5)

2

'int64'

In [6]:
a = np.array([
    [0, 1, 2, 3], 
    [10, 11, 12, 13], 
    [20, 21, 22, 23]
])
display(a)
display(a.shape)
display(a.ndim)
display(a.dtype.name)

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23]])

(3, 4)

2

'int64'

In [9]:
a = np.arange(1, 10).reshape(3,3)
display(a)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
display(a[2])
display(a[2].shape)

display(a[2, :])
display(a[2, :].shape)

display(a[2:, :])
display(a[2:, :].shape)

array([7, 8, 9])

(3,)

array([7, 8, 9])

(3,)

array([[7, 8, 9]])

(1, 3)

### Pandas

In [3]:
import pandas as pd
a = pd.DataFrame(
    {
        'a': [4,5,6],
        'b': [7,8,9],
        'c': [10,11,12]
    })
display(a)

b = pd.DataFrame([
    {"a":4, "b":7, "c":10},
    {"a":5, "b":8, "c":11},
    {"a":6, "b":9, "c":12},
    ])
display(b)               

a  b   c
0  4  7  10
1  5  8  11
2  6  9  12

a  b   c
0  4  7  10
1  5  8  11
2  6  9  12

In [4]:
display(type(a))

pandas.core.frame.DataFrame

In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

s = pd.Series([1,3,5,np.nan,6,8])
display(s)

dates = pd.date_range('20181001', periods=6)
display(dates)

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

DatetimeIndex(['2018-10-01', '2018-10-02', '2018-10-03', '2018-10-04',
               '2018-10-05', '2018-10-06'],
              dtype='datetime64[ns]', freq='D')

In [6]:
df = pd.DataFrame(np.random.randn(6,4), 
index=dates, columns=list('ABCD'))
display(df)

A         B         C         D
2018-10-01 -0.146349 -2.627712  1.346488  0.809042
2018-10-02  1.243867 -1.138890  1.607867  0.010740
2018-10-03 -0.703803 -0.288268  1.061496 -0.563985
2018-10-04 -1.667543  0.263388 -1.708986  0.157101
2018-10-05 -0.418661 -1.041203 -0.836336  0.881664
2018-10-06  1.202234 -0.299967  1.379248 -0.241147

In [7]:
df = pd.DataFrame(np.random.randn(6,4), columns=['A','B','C','D'], index = dates)
display(df)

display(df.loc['2018-10-03'])
display(df['B'])

A         B         C         D
2018-10-01  0.497132 -2.326480  1.681141  1.871879
2018-10-02  0.822611 -1.544150 -0.105970 -2.216315
2018-10-03  0.120350  0.147648 -1.143682 -0.401762
2018-10-04  0.244137  0.885401 -0.506264  0.028598
2018-10-05 -0.669542  1.070730 -1.225948 -0.758891
2018-10-06  0.465301 -0.294116 -0.612245  0.949752

A    0.120350
B    0.147648
C   -1.143682
D   -0.401762
Name: 2018-10-03 00:00:00, dtype: float64

2018-10-01   -2.326480
2018-10-02   -1.544150
2018-10-03    0.147648
2018-10-04    0.885401
2018-10-05    1.070730
2018-10-06   -0.294116
Freq: D, Name: B, dtype: float64

In [8]:
df = pd.DataFrame(np.random.randn(3,5), columns=['A','B','C','D','E'], index = ['student1','student2','student3'])
display(df)

A         B         C         D         E
student1 -0.494358 -0.466796 -1.545148 -2.892527 -1.052000
student2  0.693684  0.320487 -0.192905 -1.066985 -0.152599
student3 -0.645882  0.817149 -0.951591 -1.280557  0.341988

In [9]:
df2 = pd.DataFrame({ 'A' : 1.,
'B' : pd.Timestamp('20181001'),
'C' : pd.Series(2.5,index=list(range(4)),dtype='float32'),
'D' : np.array([3] * 4,dtype='int32'),
'E' : pd.Categorical(["test","train","test","train"]),
'F' : 'foo' })
display(df2)

A          B    C  D      E    F
0  1.0 2018-10-01  2.5  3   test  foo
1  1.0 2018-10-01  2.5  3  train  foo
2  1.0 2018-10-01  2.5  3   test  foo
3  1.0 2018-10-01  2.5  3  train  foo